[workspace]
members = [
    "video_01_the_diagram",
    "video_02_tdd_ownership"
    "video_03_bad_getters"
	"video_04_methods_vs_free"
	"video_05_proliferation_of_clones"
	"video_06_closed_polymorphism"
	"video_07_open_polymorphism"
	"video_07b_hybrid_polymorphism"
	"video_08_state_machine_enums"
	"video_08b_nested_state_machines"
]
